# Generated by Django 3.0.3 on 2020-02-16 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=50, verbose_name='Tytuł książki')),
                ('book_desc', models.TextField(verbose_name='Opis książki')),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/', verbose_name='Okładka książki')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('book_likes', models.IntegerField(default=0, verbose_name='Ocena')),
                ('book_author', models.ManyToManyField(to='books.Author', verbose_name='Autor/Autorzy')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Category', verbose_name='Kategoria')),
            ],
        ),
    ]
