# Generated by Django 3.0.3 on 2020-02-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200219_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, null=True, upload_to='covers/%Y/%m/%D/', verbose_name='Okładka książki'),
        ),
    ]
