# Generated by Django 3.0.3 on 2020-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autorzy'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Książkę', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Komentarz', 'verbose_name_plural': 'Komentarze'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Ocena', 'verbose_name_plural': 'Oceny'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_dislikes',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_likes',
        ),
        migrations.AddField(
            model_name='author',
            name='description',
            field=models.TextField(default='Brak opisu', verbose_name='Opis autora'),
        ),
    ]
