# Generated by Django 3.0.3 on 2020-02-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200216_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.Book', verbose_name='Książka'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500, verbose_name='Treść komentarza'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
    ]
