# Generated by Django 3.0.3 on 2020-08-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200612_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_rate',
            field=models.FloatField(null=True, verbose_name='Ocena książki(%)'),
        ),
    ]
