# Generated by Django 3.0.3 on 2020-08-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_book_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_rate',
            field=models.IntegerField(null=True, verbose_name='Ocena książki(%)'),
        ),
    ]
