# Generated by Django 3.0.3 on 2020-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200219_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_height',
            field=models.IntegerField(default='400', verbose_name='Wysokość okładki (w px)'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_width',
            field=models.IntegerField(default='200', verbose_name='Szerokość okładki (w px)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.ImageField(blank=True, height_field=models.IntegerField(default='400', verbose_name='Wysokość okładki (w px)'), null=True, upload_to='covers/%Y/%m/%D/', verbose_name='Okładka książki', width_field=models.IntegerField(default='200', verbose_name='Szerokość okładki (w px)')),
        ),
    ]
