# Generated by Django 3.0.3 on 2020-02-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200219_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Minusy'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_height',
            field=models.PositiveIntegerField(default='400', verbose_name='Wysokość okładki (w px)'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Plusy'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_width',
            field=models.PositiveIntegerField(default='200', verbose_name='Szerokość okładki (w px)'),
        ),
    ]
